app:
    resource: "@AppBundle/Controller/"
    type:     annotation

default:
    path:     /home
    defaults: { _controller: AppBundle:Default:index }

account_register:
    path:     /register
    defaults: { _controller: AppBundle:Account:register }

account_create:
    path:     /register/create
    defaults: { _controller: AppBundle:Account:create }

login:
    pattern:   /login
    defaults:  { _controller: AppBundle:Security:login }

login_check:
    pattern:   /login_check

repair_orders:
    path:     /repair_orders
    defaults: { _controller: AppBundle:RepairOrder:index }

repairorder_new:
    path:     /repair_orders/new
    defaults: { _controller: AppBundle:RepairOrder:new }

repairorder_create:
    path:     /repair_orders/create
    defaults: { _controller: AppBundle:RepairOrder:create }

repairorder_delete:
    path:     /repair_orders/{id}/delete
    defaults: { _controller: AppBundle:RepairOrder:delete }

repairorder_remove:
    path:     /repair_orders/{id}/remove
    defaults: { _controller: AppBundle:RepairOrder:remove }

repairorder_edit:
    path:     /repair_orders/{id}/edit
    defaults: { _controller: AppBundle:RepairOrder:edit }

repairorder_show:
    path:     /repair_orders/{id}
    defaults: { _controller: AppBundle:RepairOrder:show }

profile:
    path:     /profile
    defaults: { _controller: AppBundle:Profile:index }
logout:
    path:     /logout