app:
    resource: "@AppBundle/Controller/"
    type:     annotation

default:
    pattern:     /home
    defaults: { _controller: AppBundle:Default:index }

account_register:
    pattern:     /register
    defaults: { _controller: AppBundle:Account:register }

login:
    pattern:   /login
    defaults:  { _controller: AppBundle:Security:login }

login_check:
    pattern:   /login_check
    defaults:  { _controller: AppBundle:Security:loginCheck }

repair_orders:
    pattern:     /repair_orders
    defaults: { _controller: AppBundle:RepairOrder:index }

repairorder_new:
    pattern:     /repair_orders/new
    defaults: { _controller: AppBundle:RepairOrder:new }

repairorder_create:
    pattern:     /repair_orders/create
    defaults: { _controller: AppBundle:RepairOrder:create }

repairorder_delete:
    pattern:     /repair_orders/{id}/delete
    defaults: { _controller: AppBundle:RepairOrder:delete }

repairorder_remove:
    pattern:     /repair_orders/{id}/remove
    defaults: { _controller: AppBundle:RepairOrder:remove }

repairorder_edit:
    pattern:     /repair_orders/{id}/edit
    defaults: { _controller: AppBundle:RepairOrder:edit }

repairorder_show:
    pattern:     /repair_orders/{id}
    defaults: { _controller: AppBundle:RepairOrder:show }

profile:
    pattern:     /profile
    defaults: { _controller: AppBundle:Profile:index }

logout:
    pattern:     /logout