app:
    resource: "@AppBundle/Controller/"
    type:     annotation

default:
    pattern:     /home
    defaults: { _controller: AppBundle:Default:index }

account_register:
    pattern:     /register
    defaults: { _controller: AppBundle:Account:register }

login:
    pattern:   /login
    defaults:  { _controller: AppBundle:Security:login }

login_check:
    pattern:   /login_check
    defaults:  { _controller: AppBundle:Security:loginCheck }

repair_orders:
    pattern:     /repair_orders
    defaults: { _controller: AppBundle:RepairOrder:index }

repairorder_new:
    pattern:     /repair_orders/new
    defaults: { _controller: AppBundle:RepairOrder:new }

repairorder_delete:
    pattern:     /repair_orders/{id}/delete
    defaults: { _controller: AppBundle:RepairOrder:delete }

repairorder_remove:
    pattern:     /repair_orders/{id}/remove
    defaults: { _controller: AppBundle:RepairOrder:remove }

repairorder_edit:
    pattern:     /repair_orders/{id}/edit
    defaults: { _controller: AppBundle:RepairOrder:edit }

repairorder_show:
    pattern:     /repair_orders/{id}
    defaults: { _controller: AppBundle:RepairOrder:show }

profile:
    pattern:     /profile
    defaults: { _controller: AppBundle:Profile:index }

getPlacesByCompanyName:
    pattern:     /getPlacesByCompanyName
    defaults: { _controller: AppBundle:Place:getPlacesByCompanyName }

manager:
    pattern:   /manager
    defaults:  { _controller: AppBundle:Manager:index }

manager_users:
    pattern:   /manager/users
    defaults:  { _controller: AppBundle:Manager:usersManager }

manager_users_create:
    pattern:   /manager/users/new
    defaults:  { _controller: AppBundle:Manager:usersCreateManager }

manager_users_show:
    pattern:   /manager/users/{id}
    defaults:  { _controller: AppBundle:Manager:usersShowManager }

manager_users_delete:
    pattern:   /manager/users/{id}/delete
    defaults:  { _controller: AppBundle:Manager:usersDeleteManager }

manager_users_edit:
    pattern:   /manager/users/{id}/edit
    defaults:  { _controller: AppBundle:Manager:usersEditManager }

manager_companies:
    pattern:   /manager/companies
    defaults:  { _controller: AppBundle:Manager:companiesManager }

manager_places:
    pattern:   /manager/places
    defaults:  { _controller: AppBundle:Manager:placesManager }

manager_places_create:
    pattern:   /manager/places/new
    defaults:  { _controller: AppBundle:Manager:placesCreateManager }

manager_places_show:
    pattern:   /manager/places/{id}
    defaults:  { _controller: AppBundle:Manager:placesShowManager }

manager_places_delete:
    pattern:   /manager/places/{id}/delete
    defaults:  { _controller: AppBundle:Manager:placesDeleteManager }

manager_places_edit:
    pattern:   /manager/places/{id}/edit
    defaults:  { _controller: AppBundle:Manager:placesEditManager }


logout:
    pattern:     /logout
