app:
    resource: "@AppBundle/Controller/"
    type:     annotation

default:
    path:     /home
    defaults: { _controller: AppBundle:Default:index }

account_register:
    path:     /register
    defaults: { _controller: AppBundle:Account:register }

account_create:
    path:     /register/create
    defaults: { _controller: AppBundle:Account:create }

login:
    pattern:   /login
    defaults:  { _controller: AppBundle:Security:login }

login_check:
    pattern:   /login_check

repair_orders:
    path:     /repair_orders
    defaults: { _controller: AppBundle:RepairOrder:index }

repairorder_new:
    path:     /repair_orders/new
    defaults: { _controller: AppBundle:RepairOrder:create }