security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        index:
            pattern: ^/home$
            anonymous: ~
        profile:
            pattern: ^/profile$
            anonymous: ~
        register:
            pattern: ^/register$
            anonymous: ~
        register_create:
            pattern: ^/register/create$
            anonymous: ~
        login:
            pattern:   ^/login$
            anonymous: ~
        repair_orders:
            pattern: ^/repair_orders$
            anonymous: ~
        repairorder_new:
            pattern: ^/repair_orders/new$
            anonymous: ~
        repairorder_create:
            pattern: ^/repair_orders/create$
            anonymous: ~
        repairorder_delete:
            pattern: ^/repair_orders/{id}/delete$
            anonymous: ~
        repairorder_remove:
            pattern: ^/repair_orders/{id}/remove$
            anonymous: ~
        repairorder_edit:
            pattern: ^/repair_orders/{id}/edit$
            anonymous: ~
        repairorder_show:
            pattern: ^/repair_orders/{id}$
            anonymous: ~
        secured_area:
            pattern:    ^/
            form_login: ~
            logout:
                path:   /logout
                target: /home
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            pattern:    ^/
            anonymous: ~
            http_basic: ~
            provider: our_db_provider
            form_login:
                login_path: /login
                check_path: /login_check
                remember_me: true
            remember_me:
                key:      "%secret%"
                lifetime: 604800 # 1 week in seconds
                path:     /
                domain:   ~
    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }