security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        our_db_provider:
            entity:
                class: AppBundle:User

    firewalls:
#        public:
#            pattern:  ^/(home|profile|register|login|repair_orders|repair_orders/new|repair_orders/create|repair_orders/{id}/delete|reset-password|change-password|user/search|api/doc/*)$
#            security: false
#            anonymous: ~

        public:
            pattern:  ^/(home|register)$
            security: false
            anonymous: ~

        login_firewall:
            pattern:   ^/login$
            anonymous: ~
        secured_area:
            pattern:    ^/
            form_login: ~
            logout:
                path:   /logout
                target: /home

        default:
            pattern:    ^/
            anonymous: ~
            http_basic: ~
            provider: our_db_provider
            form_login:
                login_path: /login
                check_path: /login_check
                remember_me: true
            remember_me:
                key:      "%secret%"
                lifetime: 604800 # 1 week in seconds
                path:     /
                domain:   ~

#        repairorder_remove:
#            pattern: ^/repair_orders/{id}/remove$
#            anonymous: ~
#        repairorder_edit:
#            pattern: ^/repair_orders/{id}/edit$
#            anonymous: ~
#        repairorder_show:
#            pattern: ^/repair_orders/{id}$
#            anonymous: ~

        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }