security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        index_firewall:
            pattern: ^/home$
            anonymous: ~
        register_firewall:
            pattern: ^/register$
            anonymous: ~
        register_create_firewall:
            pattern: ^/register/create$
            anonymous: ~
        login_firewall:
            pattern:   ^/login$
            anonymous: ~
        repair_orders_firewall:
            pattern: ^/repair_orders$
            anonymous: ~
        secured_area:
            pattern:    ^/
            form_login: ~
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            pattern:    ^/
            anonymous: ~
            http_basic: ~
            provider: our_db_provider
            form_login:
                login_path: /login
                check_path: /login_check
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register/create, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/repair_orders, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }