AppBundle\Entity\RepairOrder:
    properties:
        description:
            - NotBlank:
                message: 'Description should not be blank'
                groups: [repairOrder]

AppBundle\Entity\User:
    properties:
        name:
            - NotBlank:
                message: 'Name should not be blank'
                groups: [user]

