app:
    resource: "@AppBundle/Controller/"
    type:     annotation

default:
    pattern:     /home
    defaults: { _controller: AppBundle:Default:index }

account_register:
    pattern:     /register
    defaults: { _controller: AppBundle:Account:register }

email_confirmation:
    pattern:     /email_confirmation/{id}
    defaults: { _controller: AppBundle:User:emailConfirmation }

login:
    pattern:   /login
    defaults:  { _controller: AppBundle:Security:login }

login_check:
    pattern:   /login_check
    defaults:  { _controller: AppBundle:Security:loginCheck }

companies:
    pattern: /companies
    defaults:  { _controller: AppBundle:Company:index }

users:
    pattern: /users
    defaults:  { _controller: AppBundle:User:index }


repair_orders:
    pattern:     /repair_orders
    defaults: { _controller: AppBundle:RepairOrder:index }

repairorder_new:
    pattern:     /repair_orders/new
    defaults: { _controller: AppBundle:RepairOrder:new }

repairorder_delete:
    pattern:     /repair_orders/{id}/delete
    defaults: { _controller: AppBundle:RepairOrder:delete }

repairorder_remove:
    pattern:     /repair_orders/{id}/remove
    defaults: { _controller: AppBundle:RepairOrder:remove }

repairorder_edit:
    pattern:     /repair_orders/{id}/edit
    defaults: { _controller: AppBundle:RepairOrder:edit }

repairorder_show:
    pattern:     /repair_orders/{id}
    defaults: { _controller: AppBundle:RepairOrder:show }

repairorder_assign:
    pattern:     /repair_orders/{id}/assign
    defaults: { _controller: AppBundle:RepairOrder:assign }

repairorder_assign_accept:
    pattern:     /repair_orders/{orderId}/assign/{engineerId}
    defaults: { _controller: AppBundle:RepairOrder:assignAccept }

repairorder_start:
    pattern:     /repair_orders/{id}/start
    defaults: { _controller: AppBundle:RepairOrder:start }

repairorder_finish:
    pattern:     /repair_orders/{id}/finish
    defaults: { _controller: AppBundle:RepairOrder:finish }

repairorder_close:
    pattern:     /repair_orders/{id}/close
    defaults: { _controller: AppBundle:RepairOrder:close }

repairorder_reopen:
    pattern:     /repair_orders/{id}/reopen
    defaults: { _controller: AppBundle:RepairOrder:reopen }

repairorder_history:
    pattern:     /repair_orders/{id}/history
    defaults: { _controller: AppBundle:RepairOrder:history }

profile:
    pattern:     /profile
    defaults: { _controller: AppBundle:Profile:index }

getPlacesByCompanyName:
    pattern:     /getPlacesByCompanyName
    defaults: { _controller: AppBundle:Place:getPlacesByCompanyName }

manager:
    pattern:   /manager
    defaults:  { _controller: AppBundle:Manager:index }

manager_users:
    pattern:   /manager/users
    defaults:  { _controller: AppBundle:Manager:usersManager }

manager_users_create:
    pattern:   /manager/users/new
    defaults:  { _controller: AppBundle:Account:register }

manager_users_show:
    pattern:   /manager/users/{id}
    defaults:  { _controller: AppBundle:Manager:usersShowManager }

manager_users_delete:
    pattern:   /manager/users/{id}/delete
    defaults:  { _controller: AppBundle:Manager:usersDeleteManager }

manager_users_edit:
    pattern:   /manager/users/{id}/edit
    defaults:  { _controller: AppBundle:Manager:usersEditManager }

manager_companies:
    pattern:   /manager/companies
    defaults:  { _controller: AppBundle:Manager:companiesManager }

manager_companies_create:
    pattern:   /manager/companies/new
    defaults:  { _controller: AppBundle:Manager:companiesCreateManager }

manager_companies_show:
    pattern:   /manager/companies/{id}
    defaults:  { _controller: AppBundle:Manager:companiesShowManager }

manager_companies_delete:
    pattern:   /manager/companies/{id}/delete
    defaults:  { _controller: AppBundle:Manager:companiesDeleteManager }

manager_companies_edit:
    pattern:   /manager/companies/{id}/edit
    defaults:  { _controller: AppBundle:Manager:companiesEditManager }

manager_places:
    pattern:   /manager/places
    defaults:  { _controller: AppBundle:Manager:placesManager }

manager_places_create:
    pattern:   /manager/places/new
    defaults:  { _controller: AppBundle:Manager:placesCreateManager }

manager_places_show:
    pattern:   /manager/places/{id}
    defaults:  { _controller: AppBundle:Manager:placesShowManager }

manager_places_delete:
    pattern:   /manager/places/{id}/delete
    defaults:  { _controller: AppBundle:Manager:placesDeleteManager }

manager_places_edit:
    pattern:   /manager/places/{id}/edit
    defaults:  { _controller: AppBundle:Manager:placesEditManager }


logout:
    pattern:     /logout
