security:
    role_hierarchy:
        ROLE_MANAGER: ROLE_USER
        ROLE_ENGINEER: ROLE_USER
        ROLE_CUSTOMER: ROLE_USER

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
        api_key_user_provider:
            id: api_key_user_provider

    firewalls:
        public:
            pattern:  ^/(home|register|registerSuccess|companies|companies/[0-9]+/places|users|email_confirmation|authorize)$
            security: false
            anonymous: ~

        secured_area:
            pattern: ^/
            methods: [GET, POST, PUT, DELETE, TRACE, HEAD, CONNECT]
            stateless: true
            simple_preauth:
                authenticator: apikey_authenticator
            provider: api_key_user_provider

        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/authorize, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
        - { path: ^/manager, roles: ROLE_MANAGER }