# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    api_key_user_provider:
        class: AppBundle\Security\ApiKeyUserProvider

    apikey_authenticator:
        class:  AppBundle\Security\ApiKeyAuthenticator
        public: false

    security.access.repairorder_voter:
        class:      AppBundle\Security\Authorization\Voter\RepairOrderVoter
        public:     false
        tags:
           - { name: security.voter }

    form.order.type:
        class: AppBundle\Form\Type\RepairOrderType
        arguments: [@security.token_storage]
        tags:
            - { name: form.type, alias: order_type }